set number
set splitbelow
set splitright
set termguicolors
set background=dark

let g:netrw_banner = 0
let g:netrw_cursor = 5
let g:netrw_keepdir = 0
let g:netrw_keepj = ''
let g:netrw_list_hide = '\(^\|\s\s\)\zs\.\S\+'
let g:netrw_liststyle = 1
let g:netrw_localcopydircmd = 'cp -r'

let g:everforest_background = 'medium'
let g:everforest_better_performance = 1

colorscheme everforest
syntax on
