* dotfiles

Dotfiles for *nix and Windows systems.

- ~managed-*~ are for Linux, managed by GNUStow
- ~unmanaged-*~ are not specified

Package names are those in [[https://archlinux.org/][Arch Linux]] and
[[https://aur.archlinux.org/][AUR]] if not otherwise noted.

This dotfiles will probably not work for you since there are many hard-coded
names that doesn't exist on your machine. For reference only.

** Applying

#+BEGIN_SRC sh
git clone git@github.com:vollowx/dotfiles.git && cd ./dotfiles
mkdir -p ~/.config ~/.local/share ~/.local/bin
mkdir -p ~/Documents/Mail
mkdir -p ~/Downloads
mkdir -p ~/Music
mkdir -p ~/Pictures/Wallpapers
mkdir -p ~/Pictures/Screenshots
mkdir -p ~/Videos/Screencasts
stow -vRt ~ managed-cli managed-gui
sudo cp -r unmanaged-root/. /
#+END_SRC

~stow bash-completion pkgfile unzip unrar 7zip go~

#+BEGIN_SRC sh
go install go.senan.xyz/untree@latest
sudo pkgfile --update
#+END_SRC

~htop fd ripgrep newsboat neomutt~

~mpd~ ~mpc ncmpcpp mpd-discord-rpc mpdscribble~

~lf~ ~bat catimg chafa ffmpegthumbnailer transmission-cli~

~neovim~ ~lua-language-server stylua shfmt prettier~

~sway~ ~swaybg swayidle swaylock sway-contrib waybar dunst blueman~

~xdg-desktop-portal-wlr xdg-desktop-portal-gtk polkit-gnome~

~foot zathura~

~fcitx5 fcitx5-rime rime-ice rime-pinyin-moegirl qutebrowser gimp~

*** Audio

~pipewire pipewire-alsa pipewire-jack pipewire-pulse~

This also installs ~pipewire-audio pipewire-session-manager wireplumber~,
and the ~systemd~-based auto-start is managed in
~@/home-gui/.config/systemd~.

*** Bluetooth

~bluez bluez-utils~

#+BEGIN_SRC sh
sudo systemctl enable bluetooth.service
#+END_SRC

~blueman~ is for the GUI manager and applet, the applet is used in Waybar.

*** Gaming

~steam proton-ge-custom-bin~

#+BEGIN_SRC sh
sudo usermod <username> -aG games
#+END_SRC

~xpadneo-dkms linux-header~

For Xbox controllers e.g. Xbox Series X/S Controller,
[[https://github.com/atar-axis/xpadneo][xpadneo]] is necessary to make them
function remotely. Without it, they can only be used plugging in (~xpad~
works in that case). +Stay sway from me cables :)+

*** GTK

~adw-gtk-theme~

#+BEGIN_SRC sh
./scripts/update-gsettings.sh
#+END_SRC

*** Hibernate

Power button config is in ~@/root~

#+BEGIN_SRC
# /etc/mkinitcpio.conf
HOOKS=(...filesystems resume fsck...)
#+END_SRC

*** QT

~kvantum kvantum-theme-libadwaita-git~

*** Samba

~samba~

#+BEGIN_SRC sh
sudo smbpasswd -a <username>
sudo systemctl enable --now smb
#+END_SRC

- [[https://wiki.archlinux.org/title/Samba][Samba Arch Wiki]]
- [[https://blog.fernvenue.com/archives/samba-read-only-issue-on-ios/][Samba folder read only on iOS 18.5+]]

*** Virtualization

~libvirt qemu-base virt-manager bridge-utils dnsmasq~

#+BEGIN_SRC sh
sudo usermod <username> -aG kvm,libvrt # it will take effects after reboot
sudo systemctl enable libvirtd --now
sudo virsh net-define /etc/libvirt/qemu/networks/default.xml
sudo virsh net-autostart default
sudo virsh net-start default
#+END_SRC

To control virtual machines in command line, here are some useful ones:

#+BEGIN_SRC sh
sudo virsh list
sudo virsh shutdown <domain>
sudo virsh snapshot-create-as --domain <domain> --name "<name>"
sudo virsh snapshot-list --domain <domain>
#+END_SRC

To use tools like OpenSSH with virtual machines, here is how to get the IP:

#+BEGIN_SRC sh
sudo virsh net-list
sudo virsh net-dhcp-leases default
#+END_SRC

- [[https://www.debugpoint.com/kvm-share-folder-windows-guest/][Sharing folder with Windows guest]]

** Acknowledgements

- [[https://github.com/Bekaboo/dots][bekaboo/dots]], for many Neovim plugins and configurations, etc
