require('catppuccin').setup({
  term_colors = true,
  default_integrations = false,
  auto_integrations = true,
  integrations = {
    treesitter = true,
    native_lsp = {
      enabled = true,
      virtual_text = {
        errors = { 'italic' },
        hints = { 'italic' },
        warnings = { 'italic' },
        information = { 'italic' },
      },
      underlines = {
        errors = { 'undercurl' },
        hints = { 'undercurl' },
        warnings = { 'undercurl' },
        information = { 'undercurl' },
      },
      inlay_hints = { background = true },
    },
  },
  color_overrides = {
    mocha = {
      rosewater = '#ff8389',
      flamingo = '#ff8389',
      red = '#ff8389',
      maroon = '#ff8389',
      pink = '#ff7eb6',
      mauve = '#be95ff',
      peach = '#d44a1c',
      yellow = '#ab8600',
      green = '#08bdba',
      teal = '#33b1ff',
      sky = '#33b1ff',
      sapphire = '#33b1ff',
      blue = '#78a9ff',
      lavender = '#78a9ff',
      text = '#ffffff',
      subtext1 = '#f4f4f4',
      subtext0 = '#e0e0e0',
      overlay2 = '#adadad',
      overlay1 = '#949494',
      overlay0 = '#7a7a7a',
      surface2 = '#4f4f4f',
      surface1 = '#383838',
      surface0 = '#2e2e2e',
      base = '#161616',
      mantle = '#0d0d0d',
      crust = '#000000',
    },
    latte = {
      rosewater = '#da1e28',
      flamingo = '#da1e28',
      red = '#da1e28',
      maroon = '#da1e28',
      pink = '#d02670',
      mauve = '#8a3ffc',
      peach = '#d44a1c',
      yellow = '#ab8600',
      green = '#007d79',
      teal = '#1192e8',
      sky = '#1192e8',
      sapphire = '#1192e8',
      blue = '#0f62fe',
      lavender = '#0f62fe',
      text = '#000000',
      subtext1 = '#404040',
      subtext0 = '#474747',
      overlay2 = '#575757',
      overlay1 = '#595959',
      overlay0 = '#737373',
      surface2 = '#8c8c8c',
      surface1 = '#d1d1d1',
      surface0 = '#e6e6e6',
      base = '#FFFFFF',
      mantle = '#f2f2f2',
      crust = '#ebebeb',
    },
  },
  styles = {
    comments = { 'italic' },
    conditionals = { 'italic' },
    functions = { 'italic' },
    keywords = { 'italic' },
    numbers = { 'bold' },
    types = { 'bold' },
  },
  highlight_overrides = {
    all = function(c)
      return {
        CursorLineNr = { fg = c.mauve, style = { 'bold' } },
        PmenuSel = { bg = c.surface0, fg = '' },
        Pmenu = { bg = c.mantle },
        PmenuSbar = { bg = c.crust },
        PmenuThumb = { bg = c.surface0 },
        VertSplit = { fg = c.base },
        StatusLine = { bg = c.mantle, fg = c.subtext1 },

        -- carbon
        Structure = { fg = c.pink },
        StorageClass = { fg = c.pink },
        Type = { fg = c.pink, style = { 'bold' } },
        Constant = { fg = c.text, style = { 'bold' } },
        Number = { fg = c.text },
        Float = { fg = c.text },
        Boolean = { fg = c.pink },
        ['@function.builtin'] = { fg = c.pink },
        ['@method'] = { fg = c.pink },
        ['@constant'] = { fg = c.text, style = { 'bold' } },
        ['@variable.builtin'] = { fg = c.pink },
        ['@type.builtin'] = { fg = c.pink, style = { 'bold' } },
        ['@tag.attribute.tsx'] = { fg = c.mauve, style = { 'italic' } },
        ['@tag.attribute'] = { fg = c.mauve, style = { 'italic' } },
        ['@tag.builtin.tsx'] = { fg = c.mauve },
      }
    end,
  },
})
