local config = {
  root = vim.g.package_path,
  lockfile = vim.g.package_lock,
  defaults = { lazy = true },
  checker = { enabled = false },
  change_detection = { notify = false },
  install = { colorscheme = { 'macro' } },
  dev = { path = '~/Documents' },
  ui = {
    backdrop = 100,
    size = { width = 0.7, height = 0.74 },
    border = 'single',
    icons = {
      cmd = 'cmd:',
      config = 'config:',
      event = 'event:',
      ft = 'ft:',
      init = 'init:',
      import = 'import:',
      keys = 'keys:',
      lazy = '(H) ',
      loaded = '[x]',
      not_loaded = '[ ]',
      plugin = 'dep of:',
      runtime = 'runtime:',
      require = 'require:',
      source = 'source:',
      start = 'start:',
      task = 'task:',
      list = { '' },
    },
  },
}

require('lazy').setup({ import = 'modules' }, config)
